### ISSUE TITLE
Authentication Error

### ISSUE THREAD

**Issue by ssureshr** [Raukdv/Search-Email-With-imaplib#1]
Its giving an authentication error...any guidance would be helpful...i am able to login normally on browser

**Comment by Raukdv** [comment]
Hello, If it is for authentication, check if you have activated the class for third party gmail applications.

Also check that your Gmail has the IMAP option enabled in the Forwarding and POP/IMAP settings.

For third password app check this [https://support.google.com/mail/answer/185833?hl=en](url)

For IMAP/POP check this [https://support.google.com/mail/answer/7126229?hl=en#zippy=%2Cstep-check-that-imap-is-turned-on](url)

in this line -> 123: 

emailer = EmailChecker(user='user@gmail.com', password='app-password', tag='Inbox')

the user its your gmail and the password its your new password from third party gmail applications.
